import { RoommateProfile } from "./types";

export const SEED_ROOMMATE_PROFILES: RoommateProfile[] = [
  {
    id: "rm-1",
    name: "Alex",
    program: "Engineering, 2nd year",
    budgetMin: 600,
    budgetMax: 900,
    moveInMonth: "2025-09",
    dealbreakers: ["smoking-free"],
    cleanliness: "high",
    sleepSchedule: "early",
    guests: "low",
    aboutMe: "Focused on academics. Like to keep things tidy and quiet during the week.",
    createdAt: 0,
  },
  {
    id: "rm-2",
    name: "Jordan",
    program: "Commerce, 3rd year",
    budgetMin: 700,
    budgetMax: 1000,
    moveInMonth: "2025-09",
    dealbreakers: ["smoking-free", "quiet"],
    cleanliness: "medium",
    sleepSchedule: "medium",
    guests: "medium",
    aboutMe: "Pretty easy-going. I study at the library most days and like having friends over on weekends.",
    createdAt: 0,
  },
  {
    id: "rm-3",
    name: "Priya",
    program: "Life Sciences, 1st year",
    budgetMin: 500,
    budgetMax: 750,
    moveInMonth: "2025-09",
    dealbreakers: ["pet-free", "smoking-free"],
    cleanliness: "high",
    sleepSchedule: "early",
    guests: "low",
    aboutMe: "First year looking for a calm living environment. Early riser and I keep common areas clean.",
    createdAt: 0,
  },
  {
    id: "rm-4",
    name: "Marcus",
    program: "Computer Science, 4th year",
    budgetMin: 800,
    budgetMax: 1200,
    moveInMonth: "2025-09",
    dealbreakers: ["smoking-free"],
    cleanliness: "medium",
    sleepSchedule: "late",
    guests: "medium",
    aboutMe: "Night owl who codes late. I keep my own space clean and am respectful of shared areas.",
    createdAt: 0,
  },
  {
    id: "rm-5",
    name: "Sara",
    program: "Nursing, 2nd year",
    budgetMin: 550,
    budgetMax: 800,
    moveInMonth: "2025-05",
    dealbreakers: ["quiet", "smoking-free"],
    cleanliness: "high",
    sleepSchedule: "early",
    guests: "low",
    aboutMe: "Nursing student with early clinical shifts. Need a quiet place to sleep and study.",
    createdAt: 0,
  },
  {
    id: "rm-6",
    name: "Tyler",
    program: "Kinesiology, 3rd year",
    budgetMin: 600,
    budgetMax: 850,
    moveInMonth: "2025-09",
    dealbreakers: [],
    cleanliness: "medium",
    sleepSchedule: "medium",
    guests: "high",
    aboutMe: "Social person, on the varsity team. I like having people over but always clean up after.",
    createdAt: 0,
  },
  {
    id: "rm-7",
    name: "Emma",
    program: "English, 2nd year",
    budgetMin: 500,
    budgetMax: 700,
    moveInMonth: "2025-09",
    dealbreakers: ["smoking-free"],
    cleanliness: "medium",
    sleepSchedule: "medium",
    guests: "medium",
    aboutMe: "Looking for chill roommates who respect shared spaces. I read a lot and like quiet evenings.",
    createdAt: 0,
  },
  {
    id: "rm-8",
    name: "Wei",
    program: "Mathematics, 1st year",
    budgetMin: 600,
    budgetMax: 900,
    moveInMonth: "2025-09",
    dealbreakers: ["pet-free", "smoking-free", "quiet"],
    cleanliness: "high",
    sleepSchedule: "early",
    guests: "low",
    aboutMe: "International student looking for a focused, clean environment. I cook often and share food!",
    createdAt: 0,
  },
  {
    id: "rm-9",
    name: "Olivia",
    program: "Political Studies, 3rd year",
    budgetMin: 700,
    budgetMax: 950,
    moveInMonth: "2025-09",
    dealbreakers: ["smoking-free"],
    cleanliness: "low",
    sleepSchedule: "late",
    guests: "high",
    aboutMe: "I'm social and involved in campus clubs. A bit messy but always respectful of roommates.",
    createdAt: 0,
  },
  {
    id: "rm-10",
    name: "Liam",
    program: "Mechanical Engineering, 2nd year",
    budgetMin: 650,
    budgetMax: 900,
    moveInMonth: "2025-01",
    dealbreakers: ["smoking-free"],
    cleanliness: "medium",
    sleepSchedule: "medium",
    guests: "medium",
    aboutMe: "Looking for a winter sublet. I'm pretty balanced — study hard, relax on weekends.",
    createdAt: 0,
  },
];
