import { Pin } from "./types";

// Queen's University campus center
export const QUEENS_CAMPUS = { lat: 44.2253, lng: -76.4951 };

// 15 demo listings around Kingston, ON
export const SEED_PINS: Pin[] = [
  {
    id: "pin-1",
    lat: 44.2312,
    lng: -76.4923,
    rent: 750,
    moveInDate: "2025-09-01",
    type: "room",
    title: "Bright room near campus",
    description:
      "Spacious room in a shared 3-bedroom house, 5 min walk to campus. Laundry in-unit, big backyard.",
    address: "123 University Ave",
    bedrooms: 1,
    features: ["quiet", "pet-friendly"],
    externalLink: "https://example.com/listing-1",
    sourceType: "seeded",
    createdAt: 0,
  },
  {
    id: "pin-2",
    lat: 44.2278,
    lng: -76.5012,
    rent: 1400,
    moveInDate: "2025-09-01",
    type: "whole-unit",
    title: "2BR apartment on Alfred St",
    description:
      "Modern 2-bedroom apartment, recently renovated. Close to grocery stores and bus routes.",
    address: "45 Alfred St",
    bedrooms: 2,
    features: ["quiet", "smoking-free"],
    sourceType: "seeded",
    createdAt: 0,
  },
  {
    id: "pin-3",
    lat: 44.2335,
    lng: -76.4878,
    rent: 625,
    moveInDate: "2025-05-01",
    type: "room",
    title: "Cheap room in student house",
    description:
      "Affordable room in a 5-bedroom student house. Utilities included. Lively atmosphere.",
    address: "89 Earl St",
    bedrooms: 1,
    features: ["pet-friendly", "smoking-allowed"],
    sourceType: "seeded",
    createdAt: 0,
  },
  {
    id: "pin-4",
    lat: 44.2201,
    lng: -76.4985,
    rent: 1800,
    moveInDate: "2025-09-01",
    type: "whole-unit",
    title: "3BR townhouse near lake",
    description:
      "Beautiful townhouse with lake views. 3 bedrooms, 1.5 baths, parking included.",
    address: "210 King St W",
    bedrooms: 3,
    features: ["quiet", "pet-free", "smoking-free"],
    sourceType: "seeded",
    createdAt: 0,
  },
  {
    id: "pin-5",
    lat: 44.2289,
    lng: -76.4861,
    rent: 850,
    moveInDate: "2025-09-01",
    type: "room",
    title: "Master bedroom with ensuite",
    description:
      "Large master bedroom with private bathroom in a quiet 3-bedroom house. All inclusive.",
    address: "77 Collingwood St",
    bedrooms: 1,
    features: ["quiet", "pet-free", "smoking-free"],
    sourceType: "seeded",
    createdAt: 0,
  },
  {
    id: "pin-6",
    lat: 44.2345,
    lng: -76.4945,
    rent: 700,
    moveInDate: "2025-05-01",
    type: "room",
    title: "Cozy room on Aberdeen",
    description:
      "Small but cozy room in a well-maintained house. Great landlord, fast internet.",
    address: "34 Aberdeen St",
    bedrooms: 1,
    features: ["smoking-free"],
    sourceType: "seeded",
    createdAt: 0,
  },
  {
    id: "pin-7",
    lat: 44.2225,
    lng: -76.5045,
    rent: 2200,
    moveInDate: "2025-09-01",
    type: "whole-unit",
    title: "Luxury 2BR downtown",
    description:
      "High-end apartment in downtown Kingston. In-suite laundry, gym access, underground parking.",
    address: "15 Ontario St",
    bedrooms: 2,
    features: ["quiet", "pet-free", "smoking-free"],
    externalLink: "https://example.com/listing-7",
    sourceType: "seeded",
    createdAt: 0,
  },
  {
    id: "pin-8",
    lat: 44.2298,
    lng: -76.4902,
    rent: 675,
    moveInDate: "2025-09-01",
    type: "room",
    title: "Room in student co-op",
    description:
      "Community-oriented co-op living. Shared kitchen and common spaces. Veggie-friendly house.",
    address: "56 Division St",
    bedrooms: 1,
    features: ["pet-friendly", "smoking-free"],
    sourceType: "seeded",
    createdAt: 0,
  },
  {
    id: "pin-9",
    lat: 44.2267,
    lng: -76.4932,
    rent: 900,
    moveInDate: "2025-01-01",
    type: "room",
    title: "Furnished room - Jan sublet",
    description:
      "Fully furnished room available for winter sublet. Walk to campus in 3 minutes.",
    address: "102 Stuart St",
    bedrooms: 1,
    features: ["quiet", "smoking-free"],
    sourceType: "seeded",
    createdAt: 0,
  },
  {
    id: "pin-10",
    lat: 44.2318,
    lng: -76.5001,
    rent: 1600,
    moveInDate: "2025-09-01",
    type: "whole-unit",
    title: "Renovated 2BR on Johnson",
    description:
      "Freshly renovated with modern kitchen. Hardwood floors, big windows, great natural light.",
    address: "88 Johnson St",
    bedrooms: 2,
    features: ["pet-free", "smoking-free"],
    sourceType: "seeded",
    createdAt: 0,
  },
  {
    id: "pin-11",
    lat: 44.2241,
    lng: -76.4869,
    rent: 575,
    moveInDate: "2025-09-01",
    type: "room",
    title: "Budget room on Bagot",
    description:
      "No-frills room in a shared house. Best price in the neighborhood. 10 min to campus.",
    address: "145 Bagot St",
    bedrooms: 1,
    features: ["smoking-allowed"],
    sourceType: "seeded",
    createdAt: 0,
  },
  {
    id: "pin-12",
    lat: 44.2355,
    lng: -76.4915,
    rent: 800,
    moveInDate: "2025-05-01",
    type: "room",
    title: "May sublet - Sydenham St",
    description:
      "Available May-August. Quiet street, friendly housemates, big closet.",
    address: "23 Sydenham St",
    bedrooms: 1,
    features: ["quiet", "pet-free", "smoking-free"],
    sourceType: "seeded",
    createdAt: 0,
  },
  {
    id: "pin-13",
    lat: 44.2209,
    lng: -76.4958,
    rent: 2500,
    moveInDate: "2025-09-01",
    type: "whole-unit",
    title: "4BR house - whole unit",
    description:
      "Entire 4-bedroom house available. Two bathrooms, large kitchen, basement storage.",
    address: "300 Brock St",
    bedrooms: 4,
    features: ["pet-friendly", "smoking-free"],
    sourceType: "seeded",
    createdAt: 0,
  },
  {
    id: "pin-14",
    lat: 44.2282,
    lng: -76.4978,
    rent: 725,
    moveInDate: "2025-09-01",
    type: "room",
    title: "Room with balcony",
    description:
      "Second-floor room with private balcony. Shared kitchen and bath. Super close to campus.",
    address: "61 Clergy St",
    bedrooms: 1,
    features: ["quiet", "smoking-free"],
    sourceType: "seeded",
    createdAt: 0,
  },
  {
    id: "pin-15",
    lat: 44.2330,
    lng: -76.4960,
    rent: 950,
    moveInDate: "2025-09-01",
    type: "room",
    title: "Premium room on William St",
    description:
      "Upscale shared house with cleaning service. Private bathroom, furnished room.",
    address: "18 William St",
    bedrooms: 1,
    features: ["quiet", "pet-free", "smoking-free"],
    externalLink: "https://example.com/listing-15",
    sourceType: "seeded",
    createdAt: 0,
  },
];
